// ─── MOCK DATA ─────────────────────────────────────────────────────────────
// Replace with real API responses when connecting to Spring backend

export const MOCK_OVERALL = {
    kpis: {
        totalRevenue: 4821.34,
        totalOrders: 127,
        totalClients: 47,
        totalBooks: 6,
        totalRefunds: 203.16,
        avgRating: 4.9,
        completedOrders: 42,
        cancelledOrders: 40,
    },
    ordersByStatus: [
        { name: 'Delivered',              value: 42, color: '#198754' },
        { name: 'Delivered & Paid',       value: 8,  color: '#20c997' },
        { name: 'Cancelled',              value: 28, color: '#dc3545' },
        { name: 'Cancelled & Refunded',   value: 12, color: '#fd7e14' },
        { name: 'Paid',                   value: 21, color: '#0d6efd' },
        { name: 'Created',                value: 9,  color: '#6c757d' },
        { name: 'Ready for Pickup',       value: 7,  color: '#0dcaf0' },
    ],
    buyVsRent: [
        { name: 'Purchase', value: 74, color: '#0d6efd' },
        { name: 'Rental',   value: 26, color: '#d63384' },
    ],
    topBooksBySales: [
        { title: 'Fight Club',              sales: 19 },
        { title: '1984',                    sales: 17 },
        { title: 'The Great Gatsby',        sales: 14 },
        { title: 'To Kill a Mockingbird',   sales: 11 },
        { title: 'Brave New World',         sales: 9  },
        { title: 'Pride and Prejudice',     sales: 7  },
    ],
    topBooksByRentals: [
        { title: '1984',                    rentals: 23 },
        { title: 'To Kill a Mockingbird',   rentals: 18 },
        { title: 'Fight Club',              rentals: 12 },
        { title: 'Brave New World',         rentals: 10 },
        { title: 'The Great Gatsby',        rentals: 7  },
    ],
    topRatedBooks: [
        { title: '1984',                    rating: 5.0, reviews: 1 },
        { title: 'To Kill a Mockingbird',   rating: 5.0, reviews: 1 },
        { title: 'The Great Gatsby',        rating: 4.7, reviews: 3 },
        { title: 'Fight Club',              rating: 4.5, reviews: 4 },
        { title: 'Brave New World',         rating: 4.2, reviews: 2 },
    ],
    ordersByPickupPoint: [
        { name: 'Biblioteka Centralna',     orders: 127 },
        { name: 'Punkt Kwiatowy',           orders: 0   },
        { name: 'Galeria Express',          orders: 0   },
        { name: 'Róg Wolności',             orders: 0   },
        { name: 'Zielona Polana',           orders: 0   },
    ],
    clientGrowth: [
        { month: 'Oct', clients: 18 },
        { month: 'Nov', clients: 21 },
        { month: 'Dec', clients: 26 },
        { month: 'Jan', clients: 33 },
        { month: 'Feb', clients: 47 },
    ],
};

export const MOCK_PERIOD = {
    '7d': {
        kpis: {
            revenue:        1241.96,
            revenueChange:  18.2,
            orders:         31,
            ordersChange:   12.4,
            avgCheck:       40.06,
            avgChange:      5.1,
            refunds:        121.27,
            refundsChange:  -8.3,
            newClients:     6,
            clientsChange:  33.3,
        },
        revenueOverTime: [
            { date: 'Feb 12', revenue: 80,  refunds: 0  },
            { date: 'Feb 13', revenue: 160, refunds: 40 },
            { date: 'Feb 14', revenue: 200, refunds: 0  },
            { date: 'Feb 15', revenue: 120, refunds: 47 },
            { date: 'Feb 16', revenue: 310, refunds: 0  },
            { date: 'Feb 17', revenue: 180, refunds: 34 },
            { date: 'Feb 18', revenue: 192, refunds: 0  },
        ],
        ordersByStatus: [
            { name: 'Delivered',    value: 12, color: '#198754' },
            { name: 'Cancelled',    value: 8,  color: '#dc3545' },
            { name: 'Refunded',     value: 4,  color: '#fd7e14' },
            { name: 'Paid',         value: 5,  color: '#0d6efd' },
            { name: 'Created',      value: 2,  color: '#6c757d' },
        ],
        topBooks: [
            { title: 'Fight Club',              value: 9 },
            { title: '1984',                    value: 7 },
            { title: 'The Great Gatsby',        value: 6 },
            { title: 'To Kill a Mockingbird',   value: 5 },
            { title: 'Brave New World',         value: 4 },
        ],
    },
    '30d': {
        kpis: {
            revenue:        4821.34,
            revenueChange:  12.4,
            orders:         127,
            ordersChange:   8.1,
            avgCheck:       37.96,
            avgChange:      3.9,
            refunds:        203.16,
            refundsChange:  -5.2,
            newClients:     14,
            clientsChange:  22.0,
        },
        revenueOverTime: [
            { date: 'Jan 20', revenue: 210, refunds: 0  },
            { date: 'Jan 25', revenue: 340, refunds: 40 },
            { date: 'Feb 1',  revenue: 290, refunds: 0  },
            { date: 'Feb 5',  revenue: 480, refunds: 80 },
            { date: 'Feb 10', revenue: 520, refunds: 47 },
            { date: 'Feb 13', revenue: 390, refunds: 0  },
            { date: 'Feb 15', revenue: 610, refunds: 36 },
            { date: 'Feb 16', revenue: 710, refunds: 0  },
            { date: 'Feb 17', revenue: 440, refunds: 0  },
            { date: 'Feb 18', revenue: 831, refunds: 0  },
        ],
        ordersByStatus: [
            { name: 'Delivered',    value: 42, color: '#198754' },
            { name: 'Cancelled',    value: 28, color: '#dc3545' },
            { name: 'Refunded',     value: 12, color: '#fd7e14' },
            { name: 'Paid',         value: 21, color: '#0d6efd' },
            { name: 'Created',      value: 9,  color: '#6c757d' },
            { name: 'Ready',        value: 15, color: '#0dcaf0' },
        ],
        topBooks: [
            { title: 'Fight Club',              value: 19 },
            { title: '1984',                    value: 17 },
            { title: 'The Great Gatsby',        value: 14 },
            { title: 'To Kill a Mockingbird',   value: 11 },
            { title: 'Brave New World',         value: 9  },
        ],
    },
};