package com.example.bookstore.enums;

public enum OrderStatus {
    CREATED,
    PAID,
    READY_FOR_PICKUP,
    READY_FOR_PICKUP_UNPAID,
    DELIVERED_AND_PAID,
    DELIVERED,
    RETURNED,
    CANCELLED,
    CANCELLED_PAID,
    CANCELLED_BY_USER_PAID,
    CANCELLED_BY_USER_UNPAID,
    CANCELLED_BY_DEADLINE_PAID,
    CANCELLED_BY_DEADLINE_UNPAID
}
